import type { Metadata, Viewport } from 'next'
import { Public_Sans, IBM_Plex_Mono } from 'next/font/google'
import './globals.css'

// Self-hosted by next/font rather than linked from a CDN: the app is an offline-capable
// PWA, and a webfont fetched from fonts.gstatic.com at runtime is the one thing on the
// page that would not survive airplane mode.
//
// Public Sans for the interface — it was drawn for public-sector systems, holds up at
// small sizes, and has the German diacritics this product needs.
const sans = Public_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-sans',
  display: 'swap',
})

// Every measurement, ISYBAU code and identifier is set in mono with tabular figures, so
// columns of depths and damage codes line up down the page.
const mono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-mono',
  display: 'swap',
})
import { QueryProvider } from '@/components/providers/QueryProvider'
import { DemoGate } from '@/components/providers/DemoGate'
import { DemoSessionAttrs } from '@/components/providers/DemoSessionAttrs'
import { ServiceWorker } from '@/components/providers/ServiceWorker'
import { ICON_VERSION } from '@/lib/iconVersion'

export const metadata: Metadata = {
  title:       'Spider GIS',
  description: 'Kanalnetz — AWV Mittleres Schwarzatal',
  manifest:    '/manifest.webmanifest',
  appleWebApp: { capable: true, statusBarStyle: 'default', title: 'Spider GIS' },
  icons: {
    // The 32px is drawn at tab size rather than downsampled from 192 — the web strands
    // are a couple of pixels wide there, and a browser's box filter turns them to mush.
    //
    // ?v= is a content hash of the icon set. Without it a redraw reaches nobody: a
    // browser caches a favicon harder than almost anything, and sw.js serves /icons/
    // cache-first on top. Generated by scripts/make-icons.py.
    icon: [
      { url: `/icons/icon-32.png?v=${ICON_VERSION}`,  sizes: '32x32',   type: 'image/png' },
      { url: `/icons/icon-192.png?v=${ICON_VERSION}`, sizes: '192x192', type: 'image/png' },
    ],
    apple: [{ url: `/icons/apple-touch-icon.png?v=${ICON_VERSION}`, sizes: '180x180' }],
  },
}

export const viewport: Viewport = {
  // The app's own brand blue, the same one the mark and the icons are drawn in.
  themeColor:   '#0f4c81',
  width:        'device-width',
  initialScale: 1,
  // The map should reach the screen edges on a notched phone; the top inset is
  // absorbed by the TopBar via a rule in globals.css, not by padding the whole page.
  viewportFit: 'cover',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de" className={`${sans.variable} ${mono.variable}`}>
      <body className="flex flex-col h-screen overflow-hidden bg-surface-soft font-sans text-ink antialiased">
        <QueryProvider>
          {/*
            The real app decodes a JWT server-side via cookies() and writes the username
            into these data attributes, which TopBar reads off the DOM. cookies() is a
            dynamic server API and cannot run in a static export, so DemoSessionAttrs
            fills the same attributes on the client — keeping TopBar unmodified.
          */}
          <DemoSessionAttrs>
            <DemoGate>{children}</DemoGate>
          </DemoSessionAttrs>
        </QueryProvider>
        <ServiceWorker />
      </body>
    </html>
  )
}
