// Generated by scripts/make-icons.py — do not edit.
//
// A content hash of the icon set, hung on the icon URLs so a redraw actually
// reaches people. Favicons are cached hard by the browser, and sw.js serves
// /icons/ cache-first as well.
export const ICON_VERSION = '39c6ce3d'
